### ISSUE TITLE
Missing .cs files

### ISSUE THREAD

**Issue by djjolly** [riccardodalbelloUSZ/ESAPI_VMAT-SBRT_Complexity#1]
Dear Riccardo

Do you intend on adding the .cs files for IOM, CAM or SAS? 

I am interested in modifying the scripts to be compatible with Monaco v6, are you aware if this has already been done elsewhere? 

Kind regards
David

**Comment by riccardodalbelloUSZ** [comment]
Hi David

happy to share my C# library with several metrics calculation. 
You should give as an input: IEnumerable<Beam> Beams   (the beams you want to calculate the complexity of)
You will get as an output: List<double>    (position[0] = number of beams, positions[1]-[N-1] = metrics value for single beams, position[N] = cumulative metric value for all beams.

Hope it helps
Riccardo

[MetricsCalc.zip](https://github.com/riccardodalbelloUSZ/ESAPI_VMAT-SBRT_Complexity/files/13961989/MetricsCalc.zip)
